# data-crunch-engine task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: jeffdecola/go-gcloud-packer
    tag: latest

params:
  GCP_JEFFS_APP_SERVICE_ACCOUNT_FILE: "this will be overwritten"
  GCP_JEFFS_APP_SERVICE_ACCOUNT_EMAIL_ADDRESS: "this will be overwritten"
  GCP_JEFFS_PROJECT_ID: "this will be overwritten"
  GCE_GITHUB_VM_FILE: "this will be overwritten"
  GCE_GITHUB_VM_PUB_FILE: "this will be overwritten"

inputs:
- name: data-crunch-engine

run:
  path: ./data-crunch-engine/ci/scripts/deploy.sh
  # args: [-debug]

