# data-crunch-engine task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: data-crunch-engine

outputs:
- name: data-crunch-engine-updated

run:
  path: ./data-crunch-engine/ci/scripts/readme-github-pages.sh
  # args: [-debug]

