# data-crunch-engine task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: data-crunch-engine

outputs:
- name: coverage-results

run:
  path: ./data-crunch-engine/ci/scripts/unit-tests.sh
  # args: [-debug]
  