// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyData struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 int64    `protobuf:"varint,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Meta                 string   `protobuf:"bytes,3,opt,name=Meta,proto3" json:"Meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyData) Reset()         { *m = MyData{} }
func (m *MyData) String() string { return proto.CompactTextString(m) }
func (*MyData) ProtoMessage()    {}
func (*MyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *MyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyData.Unmarshal(m, b)
}
func (m *MyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyData.Marshal(b, m, deterministic)
}
func (m *MyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyData.Merge(m, src)
}
func (m *MyData) XXX_Size() int {
	return xxx_messageInfo_MyData.Size(m)
}
func (m *MyData) XXX_DiscardUnknown() {
	xxx_messageInfo_MyData.DiscardUnknown(m)
}

var xxx_messageInfo_MyData proto.InternalMessageInfo

func (m *MyData) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MyData) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

func (m *MyData) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type MyResult struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 int64    `protobuf:"varint,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Meta                 string   `protobuf:"bytes,3,opt,name=Meta,proto3" json:"Meta,omitempty"`
	RData                int64    `protobuf:"varint,4,opt,name=RData,proto3" json:"RData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyResult) Reset()         { *m = MyResult{} }
func (m *MyResult) String() string { return proto.CompactTextString(m) }
func (*MyResult) ProtoMessage()    {}
func (*MyResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *MyResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyResult.Unmarshal(m, b)
}
func (m *MyResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyResult.Marshal(b, m, deterministic)
}
func (m *MyResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyResult.Merge(m, src)
}
func (m *MyResult) XXX_Size() int {
	return xxx_messageInfo_MyResult.Size(m)
}
func (m *MyResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MyResult.DiscardUnknown(m)
}

var xxx_messageInfo_MyResult proto.InternalMessageInfo

func (m *MyResult) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MyResult) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

func (m *MyResult) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *MyResult) GetRData() int64 {
	if m != nil {
		return m.RData
	}
	return 0
}

type MyReply struct {
	TheReply             string   `protobuf:"bytes,1,opt,name=TheReply,proto3" json:"TheReply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyReply) Reset()         { *m = MyReply{} }
func (m *MyReply) String() string { return proto.CompactTextString(m) }
func (*MyReply) ProtoMessage()    {}
func (*MyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *MyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyReply.Unmarshal(m, b)
}
func (m *MyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyReply.Marshal(b, m, deterministic)
}
func (m *MyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyReply.Merge(m, src)
}
func (m *MyReply) XXX_Size() int {
	return xxx_messageInfo_MyReply.Size(m)
}
func (m *MyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MyReply.DiscardUnknown(m)
}

var xxx_messageInfo_MyReply proto.InternalMessageInfo

func (m *MyReply) GetTheReply() string {
	if m != nil {
		return m.TheReply
	}
	return ""
}

func init() {
	proto.RegisterType((*MyData)(nil), "main.MyData")
	proto.RegisterType((*MyResult)(nil), "main.MyResult")
	proto.RegisterType((*MyReply)(nil), "main.MyReply")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc,
	0x53, 0x72, 0xe0, 0x62, 0xf3, 0xad, 0x74, 0x49, 0x2c, 0x49, 0x14, 0xe2, 0xe3, 0x62, 0xf2, 0x74,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xf2, 0x74, 0x11, 0x12, 0xe2, 0x62, 0x01, 0x89,
	0x4b, 0x30, 0x81, 0x45, 0xc0, 0x6c, 0x90, 0x98, 0x6f, 0x6a, 0x49, 0xa2, 0x04, 0xb3, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x98, 0xad, 0x14, 0xc1, 0xc5, 0xe1, 0x5b, 0x19, 0x94, 0x5a, 0x5c, 0x9a, 0x53,
	0x42, 0xae, 0x19, 0x42, 0x22, 0x5c, 0xac, 0x41, 0x60, 0x85, 0x2c, 0x60, 0x85, 0x10, 0x8e, 0x92,
	0x2a, 0x17, 0x3b, 0xc8, 0xe4, 0x82, 0x9c, 0x4a, 0x21, 0x29, 0x2e, 0x8e, 0x90, 0x8c, 0x54, 0x30,
	0x1b, 0x6c, 0x3c, 0x67, 0x10, 0x9c, 0x9f, 0xc4, 0x06, 0xf6, 0x8f, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x93, 0x4b, 0x8d, 0xf4, 0xe1, 0x00, 0x00, 0x00,
}
